name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Change to PHP7.0
        run: sudo update-alternatives --set php /usr/bin/php7.0

      - name: Install Composer and Dependencies
        run: curl -s http://getcomposer.org/installer | php && php composer.phar self-update && php composer.phar install

      - name: Full Analysis with Coverage
        run: php composer.phar check-full
